In [ ]:
import polars as pl
import seaborn as sns

sns.set_theme(style="whitegrid")

caminho_csv = r'..\data\v1_original\raw\assuntos_recorrentes.csv'
df_assuntos = pl.read_csv(caminho_csv, separator='#')

print(f"Total de linhas e colunas: {df_assuntos.shape}")
display(df_assuntos.head())

Total de linhas e colunas: (93000, 4)

shape: (5, 4)
┌────────────────────────────┬────────────────────────────┬─────────────────────┬──────────────────┐
│ numero_processo            ┆ assunto                    ┆ classe              ┆ inteiro_teor     │
│ ---                        ┆ ---                        ┆ ---                 ┆ ---              │
│ str                        ┆ str                        ┆ str                 ┆ str              │
╞════════════════════════════╪════════════════════════════╪═════════════════════╪══════════════════╡
│ 5299393.38.2023.8.09.0051  ┆ DIREITO ADMINISTRATIVO E   ┆ PROCESSO CÍVEL E DO ┆ >>>>>inicio<<<<< │
│                            ┆ OUTRA…                     ┆ TRABALHO -…         ┆ PROCURADORIA …   │
│ 5375398.72.2021.8.09.0051  ┆ DIREITO ADMINISTRATIVO E   ┆ PROCESSO CÍVEL E DO ┆ >>>>>inicio<<<<< │
│                            ┆ OUTRA…                     ┆ TRABALHO -…         ┆ ESTADO DE GOI…   │
│ 5644722.68.2021.8.09.0051  ┆ DIREITO ADMINISTRATIVO E   ┆ PROCESSO CÍVEL E DO ┆ >>>>>inicio<<<<< │
│                            ┆ OUTRA…                     ┆ TRABALHO -…         ┆ PROCURADORIA …   │
│ 5232741.73.2022.8.09.0051  ┆ DIREITO ADMINISTRATIVO E   ┆ PROCESSO CÍVEL E DO ┆ >>>>>inicio<<<<< │
│                            ┆ OUTRA…                     ┆ TRABALHO -…         ┆ PROCURADORIA …   │
│ 5115867.72.2024.8.09.0006  ┆ DIREITO ADMINISTRATIVO E   ┆ PROCESSO CÍVEL E DO ┆ >>>>>inicio<<<<< │
│                            ┆ OUTRA…                     ┆ TRABALHO -…         ┆ EXCELENTÍSSIM…   │
└────────────────────────────┴────────────────────────────┴─────────────────────┴──────────────────┘

In [2]:
nulos = df_assuntos.null_count()
print("Valores Nulos por Coluna:")
display(nulos)

duplicados = df_assuntos.is_duplicated().sum()
print(f"\nLinhas duplicadas no dataset: {duplicados}")

if duplicados > 0:
    df_assuntos = df_assuntos.unique(subset=["numero_processo"], keep="first")
    print(f"Total de linhas após remover duplicatas: {df_assuntos.shape[0]}")

Valores Nulos por Coluna:

shape: (1, 4)
┌─────────────────┬─────────┬────────┬──────────────┐
│ numero_processo ┆ assunto ┆ classe ┆ inteiro_teor │
│ ---             ┆ ---     ┆ ---    ┆ ---          │
│ u32             ┆ u32     ┆ u32    ┆ u32          │
╞═════════════════╪═════════╪════════╪══════════════╡
│ 0               ┆ 0       ┆ 0      ┆ 0            │
└─────────────────┴─────────┴────────┴──────────────┘

Linhas duplicadas no dataset: 0

In [8]:
distribuicao_assuntos = (
    df_assuntos.group_by("assunto")
    .len(name="quantidade")
    .sort("quantidade", descending=True)
)

print(f"Total de assuntos únicos: {distribuicao_assuntos.shape[0]}")
display(distribuicao_assuntos.tail(10))

assuntos_unicos = distribuicao_assuntos.filter(pl.col("quantidade") == 1).shape[0]
print(f"\nAssuntos que aparecem apenas 1 vez: {assuntos_unicos}")

Total de assuntos únicos: 49

shape: (10, 2)
┌─────────────────────────────────┬────────────┐
│ assunto                         ┆ quantidade │
│ ---                             ┆ ---        │
│ str                             ┆ u32        │
╞═════════════════════════════════╪════════════╡
│ DIREITO CIVIL -> Sucessões -> … ┆ 2000       │
│ DIREITO ADMINISTRATIVO E OUTRA… ┆ 2000       │
│ DIREITO TRIBUTÁRIO -> Impostos… ┆ 2000       │
│ DIREITO CIVIL -> Responsabilid… ┆ 2000       │
│ DIREITO PREVIDENCIÁRIO -> Bene… ┆ 2000       │
│ DIREITO DO CONSUMIDOR -> Respo… ┆ 1000       │
│ DIREITO PROCESSUAL CIVIL E DO … ┆ 1000       │
│ DIREITO TRIBUTÁRIO -> Impostos… ┆ 1000       │
│ DIREITO CIVIL -> Obrigações ->… ┆ 1000       │
│ DIREITO DO CONSUMIDOR -> Respo… ┆ 1000       │
└─────────────────────────────────┴────────────┘

Assuntos que aparecem apenas 1 vez: 0